version: 1.0.{build}

skip_branch_with_pr: true
image: Visual Studio 2017

clone_folder: C:\Projects\NetworkAdapterManager\

configuration: Release
platform: Any CPU

before_build:
  - cd C:\Projects\NetworkAdapterManager\
  - nuget restore

build:
  project:  C:\Projects\NetworkAdapterManager\NetworkAdapterManager.sln
  verbosity: minimal
