version: 1.0.{build}

skip_branch_with_pr: true
image: Visual Studio 2017

clone_folder: C:\Projects\NetworkAdapterManager\

configuration: Release
platform: Any CPU

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: 5YPM2EiJThtN8Vyn9ZWoHn69pa4/P3dMHvZp2nBw0e2uWHf89/7ui/rk/8HsXtq5
    
before_build:
  - cd C:\Projects\NetworkAdapterManager\
  - nuget restore

build:
  project:  C:\Projects\NetworkAdapterManager\NetworkAdapterManager.sln
  verbosity: minimal
